---
- name: Playbook to manage itib's dotfiles
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: clone itib/dotfile repo
      git:
        repo: https://github.com/itiB/dotfiles.git
        dest: ~/.dotfiles
