---
- name: Playbook to manage itib's dotfiles
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - 'vars.yml'
    - 'vars/links.yml'
    - 'vars/apt.yml'
    - 'vars/git_repos.yml'

  tasks:
    - name: clone git repos
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        single_branch: yes
        version: master
      loop: "{{ git_repo }}"

    - name: Create folder
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.config/git/"
        - "~/.zsh/"
        - "~/.config/aquaproj-aqua"

    - name: Include APT package list
      include_vars: vars/apt.yml
      tags:
        - apt

    - name: Update/Upgrade apt
      become: yes
      apt:
        update_cache: true
        upgrade: dist

    - name: Manage apt packages
      become: yes
      apt:
        name: "{{ item.key }}"
        state: "{{ item.value.state | default('latest') }}"
      with_dict: "{{ apt }}"

    - name: Create dotfiles symbolic links
      file:
        src: "~/.dotfiles/{{ item.name }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links }}"

    - name: Create environment symbolic links
      when: wsl_env
      file:
        src: "{{ item.name }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { name: '/mnt/c/Users/{{ wsl_ownername }}/Desktop', dest: '~/Desktop' }
        - { name: '/mnt/c/Users/{{ wsl_ownername }}/Documents', dest: '~/Documents' }
        - { name: '/mnt/c/Users/{{ wsl_ownername }}/Downloads', dest: '~/Downloads' }

    - name: chsh
      become: yes
      command:
        "chsh -s /usr/bin/zsh"

    - name: install aqua
      become: yes
      shell:
        - "curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.1.1/aqua-installer"
        - "echo "c2af02bdd15da6794f9c98db40332c804224930212f553a805425441f8331665 aqua-installer" | sha256sum -c"
        - "chmod +x aqua-installer"
        - "./aqua-installer"
        - "rm aqua-installer"

    - name: execute aqua
      become: yes
      command:
      shell: cd ~/.config/aquaproj-aqua && aqua i -a
      args:
        chdir: "~/" # コマンド実行後にホームディレクトリに戻る
